[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_APP_URL,NEXT_PUBLIC_SANITY_DATASET,NEXT_PUBLIC_SANITY_PROJECT_ID,NEXT_LOCAL_APP_URL,SANITY_WRITE_TOKEN"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "pnpm run dev"
  targetPort = 3000
  port = 8888
